---

name: ci-workflow
on: [push, pull_request]

jobs:
  build: 
    name: build job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://dockcross/linux-armv7a
      with:
        args: make BASE='arm-cortexa8_neon-linux-gnueabihf-'
    - uses: actions/upload-artifact@master
      with:
        name: MiSTer-${{ github.sha }}
        path: ./MiSTer
    - uses: actions/upload-artifact@master
      with:
        name: mister-build-tree
        path: .
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./MiSTer
