---

name: build workflow
on: [push, pull_request]

jobs:
  build: 
    name: build job
    runs-on: ubuntu-latest
    container: alpine
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: hello world
      run: /bin/ash -c 'echo "hello world"'
    - name: cross compiler
      uses: docker://dockcross/linux-armv7
      with:
        args: make
