---

name: build workflow
on: [push, pull_request]

jobs:
  build: 
    name: build job
    runs-on: ubuntu-latest
    container: hello-world
    steps:
    - name: Test
      uses: actions/checkout@v1
    - name: container blah
      run: /hello
